/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as CompetencyRouteImport } from './routes/competency'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LearningPathRouteImport } from './routes/learning-path'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as SkillGapsRouteImport } from './routes/skill-gaps'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencyRoute = CompetencyRouteImport.update({
  id: '/competency',
  path: '/competency',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathRoute = LearningPathRouteImport.update({
  id: '/learning-path',
  path: '/learning-path',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapsRoute = SkillGapsRouteImport.update({
  id: '/skill-gaps',
  path: '/skill-gaps',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/competency': typeof CompetencyRoute
  '/dashboard': typeof DashboardRoute
  '/learning-path': typeof LearningPathRoute
  '/materials': typeof MaterialsRoute
  '/quiz': typeof QuizRoute
  '/skill-gaps': typeof SkillGapsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/competency': typeof CompetencyRoute
  '/dashboard': typeof DashboardRoute
  '/learning-path': typeof LearningPathRoute
  '/materials': typeof MaterialsRoute
  '/quiz': typeof QuizRoute
  '/skill-gaps': typeof SkillGapsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/competency': typeof CompetencyRoute
  '/dashboard': typeof DashboardRoute
  '/learning-path': typeof LearningPathRoute
  '/materials': typeof MaterialsRoute
  '/quiz': typeof QuizRoute
  '/skill-gaps': typeof SkillGapsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/competency'
    | '/dashboard'
    | '/learning-path'
    | '/materials'
    | '/quiz'
    | '/skill-gaps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/competency'
    | '/dashboard'
    | '/learning-path'
    | '/materials'
    | '/quiz'
    | '/skill-gaps'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/competency'
    | '/dashboard'
    | '/learning-path'
    | '/materials'
    | '/quiz'
    | '/skill-gaps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  CompetencyRoute: typeof CompetencyRoute
  DashboardRoute: typeof DashboardRoute
  LearningPathRoute: typeof LearningPathRoute
  MaterialsRoute: typeof MaterialsRoute
  QuizRoute: typeof QuizRoute
  SkillGapsRoute: typeof SkillGapsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competency': {
      id: '/competency'
      path: '/competency'
      fullPath: '/competency'
      preLoaderRoute: typeof CompetencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-path': {
      id: '/learning-path'
      path: '/learning-path'
      fullPath: '/learning-path'
      preLoaderRoute: typeof LearningPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gaps': {
      id: '/skill-gaps'
      path: '/skill-gaps'
      fullPath: '/skill-gaps'
      preLoaderRoute: typeof SkillGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  CompetencyRoute: CompetencyRoute,
  DashboardRoute: DashboardRoute,
  LearningPathRoute: LearningPathRoute,
  MaterialsRoute: MaterialsRoute,
  QuizRoute: QuizRoute,
  SkillGapsRoute: SkillGapsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
